Repository woowa-techcamp-2021/store-5, pull requests merged in 2021-08, with the labels that each got.

#7 [Feature/6] Component 수준의 단위 테스트를 진행하기 위한 환경 구성
  frontend/client/.gitignore
  frontend/client/jest.config.js
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/setUpTests.ts
  frontend/client/src/components/TitleLabel/TitleLabel.spec.tsx
  frontend/client/src/components/TitleLabel/TitleLabel.tsx
  frontend/client/tsconfig.json
  frontend/client/webpack.common.js
  frontend/client/webpack.dev.js
  frontend/client/webpack.prod.js
Labels: FE, 작업완료

#19 [feature/18] TypeORM 관련 패키지 설치 및 엔티티 추가
  backend/.gitignore
  backend/example.md
  backend/package.json
  backend/service/auth.service.ts
  backend/src/config/index.ts
  backend/src/constants/index.ts
  backend/src/controller/auth.controller.ts
  backend/src/database.ts
  backend/src/entity/Cart.ts
  backend/src/entity/Category.ts
  backend/src/entity/DeliveryInfo.ts
  backend/src/entity/Goods.ts
  backend/src/entity/GoodsImg.ts
  backend/src/entity/OrderItem.ts
  backend/src/entity/OrderList.ts
  backend/src/entity/Payment.ts
  backend/src/entity/Promotion.ts
  backend/src/entity/User.ts
  backend/src/entity/UserAddress.ts
  backend/src/entity/Wish.ts
  backend/src/errors/base.error.ts
  backend/src/errors/client.error.ts
  backend/src/middlewares/error.middleware.ts
  backend/src/repository/user.repository.ts
  backend/src/router/auth.router.ts
  backend/src/server.ts
  backend/src/service/auth.service.ts
  backend/src/utils/index.ts
  backend/tsconfig.json
  backend/utils/index.ts
Labels: question, BE, 작업완료

#22 [feature/9] ProductItem, ProductItemList, ProductSection Component 구현
  frontend/client/jest.config.js
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/src/App.tsx
  frontend/client/src/GlobalStyles.ts
  frontend/client/src/components/GoodsItem/GoodsItem.spec.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.spec.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.spec.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.tsx
  frontend/client/src/components/ProductItem/ProductItem.spec.tsx
  frontend/client/src/components/ProductItem/ProductItem.tsx
  frontend/client/src/components/Tag/index.tsx
  frontend/client/src/components/TitleLabel/TitleLabel.spec.tsx
  frontend/client/src/components/TitleLabel/TitleLabel.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/types/Goods.ts
Labels: FE

#26 [feature/23] Client App Jest 테스트 검사를 위한 git action 스크립트 추가
  .github/workflows/client-test-actions.yaml
Labels: 작업완료

#28 Fix: import path alias (src => @src) 수정
  frontend/client/jest.config.js
  frontend/client/src/App.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.tsx
  frontend/client/src/index.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/tsconfig.json
  frontend/client/webpack.common.js
Labels: bug, 작업완료

#31 [Feature/9] Promotion Carousel 구현 - Main Section
  frontend/client/jest.config.js
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/setUpTests.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/PromotionCarousel/PromotionCarousel.spec.tsx
  frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
  frontend/client/src/pages/Main/BannerContainer/BannerContainer.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/types/Promotion.ts
  frontend/client/webpack.common.js
Labels: FE, 작업완료

#30 [feature/12] 장바구니 페이지
  frontend/client/custom.d.ts
  frontend/client/package-lock.json
  frontend/client/src/App.tsx
  frontend/client/src/components/CheckButton/CheckButton.tsx
  frontend/client/src/components/CheckButtonWithLabel/CheckButtonWithLabel.tsx
  frontend/client/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/client/src/lib/CustomRouter.tsx
  frontend/client/src/pages/Cart/CartContainer.tsx
  frontend/client/src/pages/Cart/CartContainerWithAPI.tsx
  frontend/client/src/pages/Cart/CartContainerWithLocalstorage.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListContainer.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsAmountInput/CartGoodsAmountInput.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.spec.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.tsx
  frontend/client/src/pages/Cart/CartNoData/CartNoData.tsx
  frontend/client/src/pages/Cart/CartNoData/asset/empty-cart.png
  frontend/client/src/pages/Cart/CartOrder/CartOrder.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/Cart/EmptyCart/EmptyCart.tsx
  frontend/client/src/pages/Cart/EmptyCart/asset/empty-cart.png
  frontend/client/src/theme/theme.ts
  frontend/client/src/types/CartGoods.ts
  frontend/client/src/utils/price.ts
Labels: FE

#37 [feature/11] 상세 페이지 컴포넌트 구현 및 #35의 커스텀 줌 기능 구현
  frontend/client/src/pages/Goods/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/Goods/GoodsDetail.tsx
  frontend/client/src/pages/Goods/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/Goods/GoodsPrice/GoodsPrice.tsx
  frontend/client/src/pages/Goods/ImageList/ImageItem/ImageItem.tsx
  frontend/client/src/pages/Goods/ImageList/ImageList.spec.tsx
  frontend/client/src/pages/Goods/ImageList/ImageList.tsx
  frontend/client/src/pages/Goods/Mainimage/MainImage.tsx
  frontend/client/src/pages/Goods/Mainimage/ZoomImage.ts
Labels: FE, 작업중

#39 [feature/18] User 엔티티 수정
  backend/src/config/index.ts
  backend/src/entity/User.ts
Labels: BE

#40 [feature/9] 상품 이미지 호버 효과와 최근상품리스트를 보여주는 사이드바 구현
  frontend/client/package.json
  frontend/client/src/components/Footer/Footer.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/Tag/index.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/pages/Main/SideBar/SideBar.spec.tsx
  frontend/client/src/pages/Main/SideBar/SideBar.tsx
Labels: FE, 작업완료

#44 [feature/38] 주문/결제 페이지 우측 컨텐츠 목업 완료
  frontend/client/src/App.tsx
  frontend/client/src/components/Button/Button.tsx
  frontend/client/src/components/CheckButton/CheckButton.tsx
  frontend/client/src/components/CheckButtonWithLabel/CheckButtonWithLabel.tsx
  frontend/client/src/components/Divider/Divider.tsx
  frontend/client/src/components/HighlightedText/HighlightedText.tsx
  frontend/client/src/components/PageHeader/PageHeader.tsx
  frontend/client/src/pages/Cart/CartContainer.tsx
  frontend/client/src/pages/Cart/CartContainerWithAPI.tsx
  frontend/client/src/pages/Cart/CartContainerWithLocalstorage.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListContainer.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.spec.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.tsx
  frontend/client/src/pages/Cart/CartOrder/CartOrder.tsx
  frontend/client/src/pages/Cart/Layout/Layout.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/types/CartGoods.ts
  frontend/client/src/types/Goods.ts
Labels: FE, 작업완료

#42 [feature/11] 상세 페이지 UI 구현
  frontend/client/src/App.tsx
  frontend/client/src/pages/Goods/GoodsPrice/GoodsPrice.tsx
  frontend/client/src/pages/Goods/ImageList/ImageItem/ImageItem.tsx
  frontend/client/src/pages/Goods/ImageList/ImageList.tsx
  frontend/client/src/pages/Goods/index.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/GoodsImageSection.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageItem/ImageItem.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageList.spec.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/Mainimage/MainImage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/Mainimage/ZoomImage.ts
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/GoodsDetail/GoodsRelationList/GoodsRelationList.tsx
Labels: FE, 작업완료

#48 update: 간단한 README 작성
  README.md
Labels: 작업완료

#60 [Deploy] 자동배포 스크립트 수정입니다. OAuth를 위해 필요한 환경변수 추가작업입니다.
  .github/workflows/deploy-actions.yaml
Labels: 작업완료

#63 [Refactoring] 상품 상세 페이지 리팩토링 및 웹팩 번들링 속도 개선
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/src/components/GoodsItem/GoodsItem.spec.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.spec.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.spec.tsx
  frontend/client/src/components/Header/Header.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/GoodsImageSection.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/GoodsDetail/GoodsRelationList/GoodsRelationList.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/pages/Main/SideBar/SideBar.spec.tsx
  frontend/client/src/pages/Main/SideBar/SideBar.tsx
  frontend/client/src/types/Goods.ts
  frontend/client/webpack.common.js
Labels: FE, 작업완료

#65 배포 링크 수정
  README.md
Labels: 작업완료

#71 [feature/62] 제품 상세 조회 API, 회원 배송지 CRUD
  backend/src/controller/category.controller.ts
  backend/src/controller/goods.controller.ts
  backend/src/controller/user.controller.ts
  backend/src/database.ts
  backend/src/entity/Category.ts
  backend/src/entity/Goods.ts
  backend/src/entity/UserAddress.ts
  backend/src/errors/base.error.ts
  backend/src/middlewares/check-number-params.ts
  backend/src/middlewares/error.middleware.ts
  backend/src/middlewares/is-authenticate.ts
  backend/src/repository/category.repository.ts
  backend/src/repository/goods.repository.ts
  backend/src/repository/user.address.repository.ts
  backend/src/repository/user.repository.ts
  backend/src/router/auth.router.ts
  backend/src/router/category.router.ts
  backend/src/router/goods.router.ts
  backend/src/router/index.ts
  backend/src/router/user.router.ts
  backend/src/service/auth.service.ts
  backend/src/service/category.service.ts
  backend/src/service/goods.service.ts
  backend/src/service/user.address.service.ts
  backend/src/types/request/auth.request.ts
  backend/src/types/request/goods.request.ts
  backend/src/types/request/user.request.ts
  backend/src/types/response/goods.response.ts
  backend/src/types/response/user.response.ts
Labels: BE, 작업완료

#74 [feature/10] 카테고리별 상품 조회 화면 개발
  frontend/client/src/App.tsx
  frontend/client/src/apis/base.ts
  frontend/client/src/apis/goodsAPI.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.tsx
  frontend/client/src/components/Header/HeaderBottom/Category/SubCategoryList/SubCategoryList.tsx
  frontend/client/src/lib/CustomRouter.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoods.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/Paginator.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/utils/range.ts
Labels: FE

#70 [feature/69] css-in-js 를 위한 CustomStyledcComponent 모듈 구현
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/HeaderIconContainer.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/MyPageIcon/MyPageIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/ShoppigCartIcon/ShoppingCartIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderLogo/HeaderLogo.tsx
  frontend/client/src/components/Header/HeaderBottom/SearchContainer/AutoSearchList/AutoSearchList.tsx
  frontend/client/src/components/Header/HeaderTop/HeaderTop.tsx
  frontend/client/src/lib/CustomRouter/CustomRouter.spec.tsx
  frontend/client/src/lib/CustomRouter/CustomRouter.tsx
  frontend/client/src/lib/CustomRouter/index.ts
  frontend/client/src/lib/CustomStyledComponent/CuteomStyledComponent.spec.tsx
  frontend/client/src/lib/CustomStyledComponent/index.ts
  frontend/client/src/pages/Cart/EmptyCart/EmptyCart.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/Main/Main.tsx
Labels: FE, 작업완료

#76 [feature/64] 상품 목록 조회 API
  backend/package.json
  backend/src/controller/goods.controller.ts
  backend/src/entity/Goods.ts
  backend/src/entity/Wish.ts
  backend/src/repository/goods.repository.ts
  backend/src/repository/wish.repository.ts
  backend/src/router/goods.router.ts
  backend/src/service/goods.service.ts
  backend/src/types/Goods.ts
  backend/src/types/response/goods.response.ts
  backend/src/utils/pagination.ts
Labels: BE, 작업완료

#79 Add: Keyword 페이지로 전환
  frontend/client/src/App.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/SearchIcon/SearchIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/SearchContainer/SearchContainer.tsx
  frontend/client/src/lib/CustomRouter/CustomRouter.tsx
  frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
Labels: FE

#78 [feature/77] Category API 구현
  backend/src/controller/category.controller.ts
  backend/src/database.ts
  backend/src/repository/category.repository.ts
  backend/src/router/category.router.ts
  backend/src/router/index.ts
  backend/src/service/category.service.ts
  backend/src/types/response/category.response.ts
  frontend/client/src/apis/base.ts
  frontend/client/src/apis/categoryAPI.ts
  frontend/client/src/components/Header/HeaderBottom/Category/Category.tsx
  frontend/client/src/components/Header/HeaderBottom/Category/SubCategoryList/SubCategoryList.spec.tsx
  frontend/client/src/components/Header/HeaderBottom/Category/SubCategoryList/SubCategoryList.tsx
  frontend/client/src/types/Category.ts
Labels: BE

#81 [feature/80] 찜하기 API 1/2 (클라이언트 미연동)
  backend/src/controller/wish.controller.ts
  backend/src/entity/Wish.ts
  backend/src/repository/wish.repository.ts
  backend/src/router/index.ts
  backend/src/router/wish.router.ts
  backend/src/service/wish.service.ts
  backend/src/types/response/wish.response.ts
Labels: BE

#85 update: styled component 개선
  frontend/client/src/lib/CustomStyledComponent/index.ts
Labels: FE

#61 [feature/38] 주문/결제 페이지 좌측 기능 동작
  frontend/client/src/components/CheckButton/CheckButton.tsx
  frontend/client/src/components/CheckButtonWithLabel/CheckButtonWithLabel.tsx
  frontend/client/src/components/ConfirmModal/ConfirmModal.tsx
  frontend/client/src/components/Input/Input.tsx
  frontend/client/src/components/Topic/Topic.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressCard/AddressCard.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressCreateModal/AddressCreateModal.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressForm/AddressForm.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressFormCore/AddressFormCore.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressInfo.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressManageModal/AddressCreatePage/AddressCreatePage.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressManageModal/AddressManageModal.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressManageModal/AddressSelectPage/AddressSelectPage.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressManageModal/AddressUpdatePage/AddressUpdatePage.tsx
  frontend/client/src/pages/Order/AddressInfo/Loading/Loading.tsx
  frontend/client/src/pages/Order/AddressInfo/Modal/Modal.tsx
  frontend/client/src/pages/Order/AddressInfo/ModalBar/ModalBar.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsList.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsListItem/OrderGoodsListItem.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/types/Address.ts
  frontend/client/src/types/Goods.ts
Labels: FE, 작업완료

#87 [feature] 백엔드 express 서버 index.html로의 fallback 추가
  backend/src/server.ts
Labels: BE, 작업완료

#92 [feature/88] Cart API
  backend/src/controller/cart.controller.ts
  backend/src/repository/cart.repository.ts
  backend/src/router/cart.router.ts
  backend/src/router/index.ts
  backend/src/service/cart.service.ts
  backend/src/types/request/cart.request.ts
  backend/src/types/response/cart.response.ts
Labels: BE, 작업완료

#96 [feature/43] Admin 앱을 CI/CD 적용을 위한 작업
  .github/workflows/admin-test-actions.yaml
  .github/workflows/deploy-actions.yaml
  backend/.gitignore
  backend/package-lock.json
  backend/src/database.ts
  backend/src/server.ts
  frontend/admin/jest.config.js
  frontend/admin/setUpTests.ts
  frontend/admin/src/lib/CustomRouter/CustomRouter.spec.tsx
  frontend/admin/src/lib/CustomRouter/CustomRouter.tsx
  frontend/admin/src/lib/CustomRouter/index.ts
  frontend/admin/src/lib/CustomStyledComponent/CuteomStyledComponent.spec.tsx
  frontend/admin/src/lib/CustomStyledComponent/index.ts
  frontend/admin/src/pages/Main.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductImageUploader/ProductImagePreviews/ProductImagePreviews.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductUploadModal.tsx
  frontend/admin/webpack.common.js
  frontend/admin/webpack.dev.js
  frontend/client/src/components/Header/HeaderTop/HeaderTop.tsx
Labels: FE, BE, 작업완료

#99 [feature/93] 장바구니 페이지 API 연동
  backend/src/controller/cart.controller.ts
  backend/src/repository/cart.repository.ts
  backend/src/router/cart.router.ts
  backend/src/service/cart.service.ts
  frontend/client/src/apis/cartAPI.ts
  frontend/client/src/pages/Cart/CartContainer.tsx
  frontend/client/src/pages/Cart/CartContainerWithAPI.tsx
  frontend/client/src/pages/Cart/CartContainerWithLocalstorage.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.spec.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.tsx
  frontend/client/src/pages/Cart/CartOrder/CartOrder.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/types/Goods.ts
  frontend/client/src/utils/price.ts
Labels: FE, BE, 작업완료

#98 [feature/94] 상품 상세페이지 API 연동 1/2 (내용 및 연관 상품, 재고 조회)
  backend/src/controller/goods.controller.ts
  backend/src/repository/goods.repository.ts
  backend/src/repository/wish.repository.ts
  backend/src/router/goods.router.ts
  backend/src/service/goods.service.ts
  backend/src/types/response/goods.response.ts
  frontend/client/src/apis/goodsAPI.ts
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageItem/ImageItem.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/GoodsDetail/RelationSection/RelationSection.tsx
  frontend/client/src/types/Goods.ts
Labels: FE

#101 [feature/100] 마이 페이지 초기 레이아웃 구성과 사용자 배송정보 수정 및 생성
  backend/src/controller/user.controller.ts
  backend/src/entity/UserAddress.ts
  backend/src/router/user.router.ts
  backend/src/service/user.address.service.ts
  backend/src/types/response/user.response.ts
  frontend/admin/webpack.dev.js
  frontend/client/src/App.tsx
  frontend/client/src/apis/addressAPI.ts
  frontend/client/src/components/AddressCard/AddressCard.tsx
  frontend/client/src/components/AddressModals/AddressCreateModal/AddressCreateModal.tsx
  frontend/client/src/components/AddressModals/AddressForm/AddressForm.tsx
  frontend/client/src/components/AddressModals/AddressFormCore/AddressFormCore.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressCreatePage/AddressCreatePage.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressManageModal.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressSelectPage/AddressSelectPage.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressUpdatePage/AddressUpdatePage.tsx
  frontend/client/src/components/AddressModals/Loading/Loading.tsx
  frontend/client/src/components/AddressModals/Modal/Modal.tsx
  frontend/client/src/components/AddressModals/ModalBar/ModalBar.tsx
  frontend/client/src/components/HighlightedText/HighlightedText.tsx
  frontend/client/src/components/PrimaryButton/PrimaryButton.tsx
  frontend/client/src/lib/CustomRouter/CustomRouter.tsx
  frontend/client/src/pages/Cart/CartOrder/CartOrder.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
  frontend/client/src/pages/MyPage/MyPage.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/MyPageNavBar.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/NavItem.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/SubNav.tsx
  frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
  frontend/client/src/pages/Order/AddressInfo/AddressManageModal/AddressManageModal.tsx
  frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/types/Address.ts
Labels: FE, BE

#107 [BugFix] 상품 페이지 네이션 및 리팩토링 진행했습니다.
  backend/package-lock.json
  backend/package.json
  backend/src/server.ts
  backend/src/utils/pagination.ts
  frontend/client/src/apis/goodsAPI.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/Paginator/Paginator.tsx
  frontend/client/src/components/Tag/index.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
  frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
  frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/NavItem.tsx
  frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
  frontend/client/src/types/Goods.ts
Labels: FE

#106 [feature/95] Admin 제품 만들기 모달, API 연동 , 로딩 컴포넌트
  backend/package-lock.json
  backend/src/controller/goods.controller.ts
  backend/src/router/delivery.router.ts
  backend/src/router/goods.router.ts
  backend/uploads/0e2e55ced2a12e28e1448a1e699052fd
  backend/uploads/49a3e4b752b342812d326005b6314a02
  backend/uploads/50d2a67d0f313ab2ee7d9cb1ac7a5c19
  backend/uploads/683aba575119f1b5e4d5d30c5ff8643f
  backend/uploads/73cba968062a1ff4bd1b9587e978139c
  backend/uploads/76bc7da57ee20405767487a84256b0f9
  backend/uploads/7f9ae57f42a5cacb45628058f24259ca
  backend/uploads/8404ff549e1ebdb02b456f2827f4e0f7
  backend/uploads/87203184db6b09b9ccb40639c4edaa45
  backend/uploads/99ce7e15f594d370f1d2d9fb5941e655
  backend/uploads/9f34a4660eac601d65c4478c8fdab5b5
  backend/uploads/9f91044506d836cf32f3c0ba31c3090a
  backend/uploads/a0a30eb38b2765cbee9f2fa1c81b4e9d
  backend/uploads/aa9b70352a77d5b29653411a75297233
  backend/uploads/b418440a43ab82b9418857664720e579
  backend/uploads/bcc13cc928d2548a8e223be97b8660b7
  backend/uploads/d5c745b83e54b0c01bccfa15df4baba1
  backend/uploads/d61d3fe03c022002ce22e4e8f012977a
  backend/uploads/dbe619a8e02ae932782736790a4cfbca
  backend/uploads/e67790ffb79c8d5e335450263ea71e73
  backend/uploads/eaecd0d19563830652995305e3b33878
  backend/uploads/ef959e3f9bb938c366aa1a9e02da00b6
  backend/uploads/f8ebb0be2ca196392c301a3f0d2e6760
  frontend/admin/src/apis/base.ts
  frontend/admin/src/apis/categoryAPI.ts
  frontend/admin/src/apis/deliveryAPI.ts
  frontend/admin/src/apis/goodsAPI.ts
  frontend/admin/src/index.tsx
  frontend/admin/src/pages/Main.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/GoodsImagePreviews/GoodsImagePreviews.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/GoodsImageUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/ImageIconButton/ImageIconButton.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/PreviewImage/PreviewImage.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsDiscountUploader/GoodsDiscountUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsPriceUploader/GoodsPriceUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsStockUploader/GoodsStockUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsTitleUploader/GoodsTitleUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/UploadContentLeft.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/style.ts
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsCategoryUploader/GoodsCategoryUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsDeliveryUploader/GoodsDeliveryUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsGreenUploader/GoodsGreenUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsStateUploader/GoodsStateUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/UploadContentRight.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductImageUploader/ProductImagePreviews/ProductImagePreviews.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductImageUploader/ProductImageUploader.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductTitleUploader/ProductTitleUploader.tsx
  frontend/admin/src/portal/ProductUploadModal/ProductUploadModal.tsx
  frontend/admin/src/theme/theme.ts
  frontend/admin/src/types/Category.ts
  frontend/admin/src/types/DeliveryInfo.ts
  frontend/admin/src/types/Goods.ts
  frontend/admin/src/utils/formatNumber.ts
  frontend/admin/webpack.dev.js
  frontend/client/src/components/Loading/Loading.tsx
Labels: FE, 작업완료

#110 [feature/102] Order 생성, 조회 (title, thumbnail 추가)
  backend/src/entity/OrderItem.ts
  backend/src/repository/order.item.repository.ts
  backend/src/repository/order.list.repository.ts
  backend/src/service/order.service.ts
  backend/src/types/Order.ts
  backend/src/types/request/order.request.ts
  backend/src/types/response/order.response.ts
Labels: BE, 작업완료

#114 [feature/94] 상품 상세페이지 API 연동, 카트 모달 추가
  backend/src/controller/goods.controller.ts
  backend/src/controller/user.controller.ts
  backend/src/controller/wish.controller.ts
  backend/src/repository/goods.repository.ts
  backend/src/repository/wish.repository.ts
  backend/src/router/user.router.ts
  backend/src/router/wish.router.ts
  backend/src/service/goods.service.ts
  backend/src/types/Goods.ts
  frontend/client/empty-module.js
  frontend/client/jest.config.js
  frontend/client/src/apis/goodsAPI.ts
  frontend/client/src/apis/wishApi.ts
  frontend/client/src/components/GoodsItem/GoodsItem.spec.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/GoodsImageSection.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/Mainimage/MainImage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/Mainimage/asset/empty-img.png
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/GoodsDetail/RelationSection/RelationSection.tsx
  frontend/client/src/portal/CartModal/CartForm/CartForm.tsx
  frontend/client/src/portal/CartModal/CartModal.tsx
Labels: FE

#108 [feature/103] Recoil을 사용해 주문/결제 페이지로 상품을 전달하기
  frontend/client/src/hooks/usePushToOrderPage.ts
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsList.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsListItem/OrderGoodsListItem.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/recoil/orderState.ts
  frontend/client/src/types/Goods.ts
Labels: FE, 작업완료

#117 [feature/113] Admin 좌측 헤더 구현
  frontend/admin/custom.d.ts
  frontend/admin/public/images/logo.png
  frontend/admin/src/App.tsx
  frontend/admin/src/components/Header/DashboardIcon/DashboardIcon.tsx
  frontend/admin/src/components/Header/GoodsAdminIcon/GoodsAdminIcon.tsx
  frontend/admin/src/components/Header/Header.tsx
  frontend/admin/src/components/Header/LogoIcon/LogoIcon.tsx
  frontend/admin/src/components/Header/OrderAdminIcon/OrderAdminIcon.tsx
  frontend/admin/src/components/Header/PromotionAdminIcon/PromotionAdminIcon.tsx
  frontend/admin/src/index.css
  frontend/admin/src/index.tsx
  frontend/admin/src/lib/CustomRouter/CustomRouter.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsAdmin.tsx
  frontend/admin/src/pages/Main/Main.tsx
  frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionAdmin.tsx
  frontend/admin/src/styles/reset.css
  frontend/admin/src/types/Header.ts
  frontend/admin/src/utils/customEvent.ts
Labels: FE, 작업완료

#121 [feature/94] 상품 상세 및 상품 컴포넌트 API 연동
  backend/src/controller/goods.controller.ts
  backend/src/router/goods.router.ts
  backend/src/service/goods.service.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/portal/CartModal/CartForm/CartForm.tsx
Labels: BE

#122 [feature/120] 주문/결제 페이지 - 주문 API 연동
  backend/src/database.ts
  backend/src/repository/order.list.repository.ts
  frontend/client/src/apis/orderAPI.ts
  frontend/client/src/apis/paymentAPI.ts
  frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
  frontend/client/src/pages/Order/AfterOrder/AfterOrder.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/pages/Order/PaymentRadioSelector/PaymentRadioSelector.tsx
  frontend/client/src/types/Payment.ts
  frontend/client/src/utils/validate.ts
Labels: FE, BE, 작업완료

#124 [Deploy] 배포 파이프라인 에서 node_module 제거해서 번들링 결과만 배포
  .github/workflows/deploy-actions.yaml
  scripts/after_deploy.sh
  scripts/before_deploy.sh
Labels: bug, BE, 작업완료

#135 [feature/119] Toast 개발, OrderPage에 적용
  frontend/client/src/index.tsx
  frontend/client/src/lib/ToastProvider/Toast/Toast.tsx
  frontend/client/src/lib/ToastProvider/ToastPortalWrapper/ToastPortalWrapper.tsx
  frontend/client/src/lib/ToastProvider/ToastProvider.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
Labels: FE, 작업완료

#141 [feature/116] 관리자 상품 관리 페이지 UI 및 API연동 1차 작업 (수정, 정렬, 키워드 검색 미구현)
  backend/src/controller/goods.controller.ts
  backend/src/repository/goods.repository.ts
  backend/src/router/goods.router.ts
  backend/src/service/goods.service.ts
  backend/src/types/Goods.ts
  frontend/admin/src/App.tsx
  frontend/admin/src/apis/goodsAPI.ts
  frontend/admin/src/components/Header/Header.tsx
  frontend/admin/src/components/Paginator/Paginator.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsAdmin.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTable.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableBody.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/Search/Search.tsx
  frontend/admin/src/theme/theme.ts
  frontend/admin/src/types/Goods.ts
  frontend/admin/src/utils/dateHelper.ts
  frontend/admin/src/utils/price.ts
  frontend/admin/src/utils/range.ts
Labels: FE

#145 [feature/137] 유효하지 않은 페이지 접근 시, main 페이지로 리다이렉트하는 공용 로직 추가
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/MyPage/MyPage.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/utils/withLoggedIn.tsx
Labels: FE, 작업완료

#148 [feature/138] S3 SDK를 이용해서 S3에 이미지 업로드하기
  backend/.env.example
  backend/package-lock.json
  backend/package.json
  backend/src/config/index.ts
  backend/src/controller/goods.controller.ts
  backend/src/controller/promotion.controller.ts
  backend/src/database.ts
  backend/src/entity/Goods.ts
  backend/src/middlewares/upload-file.ts
  backend/src/router/goods.router.ts
  backend/src/router/promotion.router.ts
  backend/src/service/goods.service.ts
  backend/src/service/promotion.service.ts
  backend/src/types/request/promotion.request.ts
  backend/src/utils/aws.upload.ts
  backend/src/utils/convert.url.from.file.ts
  frontend/admin/package-lock.json
  frontend/admin/package.json
  frontend/client/src/pages/Main/Main.tsx
Labels: BE

#150 [Bug] Controller Component 방식 변경
  backend/src/controller/goods.controller.ts
  backend/src/service/goods.service.ts
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsDiscountUploader/GoodsDiscountUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsPriceUploader/GoodsPriceUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsStockUploader/GoodsStockUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/UploadContentLeft.tsx
  frontend/admin/src/utils/formatToNumber.ts
Labels: bug, 작업완료

#147 [feature/146] Toast 개선
  frontend/client/src/lib/ToastProvider/Toast/Toast.tsx
  frontend/client/src/lib/ToastProvider/ToastPortalWrapper/ToastPortalWrapper.tsx
  frontend/client/src/lib/ToastProvider/ToastProvider.tsx
Labels: FE, 작업완료

#156 [feature/152] client UX 개선 시도
  frontend/client/src/components/AddressCard/AddressCard.tsx
  frontend/client/src/components/AddressModals/AddressForm/AddressForm.tsx
  frontend/client/src/components/AddressModals/AddressFormCore/AddressFormCore.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressSelectPage/AddressSelectPage.tsx
  frontend/client/src/components/AddressModals/Loading/Loading.tsx
  frontend/client/src/components/AddressModals/Modal/Modal.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/Order/AfterOrder/AfterOrder.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/utils/composeComponent.ts
  frontend/client/src/utils/withScrollToTopOnMount.tsx
Labels: FE, 작업완료

#168 [feature/151] 대시보드- 상품 카테고리 비율 차트, TOP 상품 컴포넌트 개발 (Client-로그인,로그아웃 메인 UX 개선)
  backend/src/controller/category.controller.ts
  backend/src/controller/goods.controller.ts
  backend/src/repository/category.repository.ts
  backend/src/repository/goods.repository.ts
  backend/src/router/category.router.ts
  backend/src/router/goods.router.ts
  backend/src/service/category.service.ts
  backend/src/service/goods.service.ts
  backend/src/types/response/category.response.ts
  frontend/admin/package-lock.json
  frontend/admin/package.json
  frontend/admin/src/apis/categoryAPI.ts
  frontend/admin/src/apis/goodsAPI.ts
  frontend/admin/src/pages/Main/CategoryPieChart/CategoryPieChart.tsx
  frontend/admin/src/pages/Main/Main.tsx
  frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoods/TopSellingGoods.tsx
  frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoodsList.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsCategoryUploader/GoodsCategoryUploader.tsx
  frontend/admin/src/theme/theme.ts
  frontend/admin/src/types/Chart.ts
  frontend/admin/src/utils/convertCountOfSell.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/pages/Main/Main.tsx
Labels: FE, BE, 작업완료

#166 [feature/158, 159] 깃허브 로그인 시 프로필 이미지 URL을 가져오기, 깃허브 닉네임이 없을시, oauth가 안되는 문제 해결하기
  backend/src/controller/auth.controller.ts
  backend/src/entity/User.ts
  backend/src/repository/user.repository.ts
  backend/src/service/auth.service.ts
  frontend/client/src/apis/authAPI.ts
  frontend/client/src/hooks/useUserState.ts
  frontend/client/src/recoil/userState.ts
  frontend/client/src/types/User.ts
Labels: bug, FE, BE, 작업완료

#177 [feature/162] 이슈 기반 상세 페이지, 상품 목록 추가 개선
  backend/src/controller/goods.controller.ts
  backend/src/service/goods.service.ts
  backend/src/types/request/goods.request.ts
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTable.tsx
  frontend/admin/src/utils/dateHelper.ts
  frontend/client/custom.d.ts
  frontend/client/src/assets/empty-img.png
  frontend/client/src/assets/empty-kim.gif
  frontend/client/src/hooks/useScrollToTop.ts
  frontend/client/src/pages/CategoryGoods/CategoryGoods.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/GoodsImageSection.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/Mainimage/ZoomImage.ts
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/InfoContent/InfoContent.tsx
  frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
  frontend/client/src/types/Goods.ts
Labels: FE, BE, 작업완료

#180 [feature/118] 프로모션 조회수 API 구현 및 클라이언트 연동
  backend/src/controller/promotion.controller.ts
  backend/src/entity/Promotion.ts
  backend/src/repository/promotion.repository.ts
  backend/src/router/promotion.router.ts
  backend/src/service/promotion.service.ts
  frontend/client/src/apis/promotionAPI.ts
  frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
  frontend/client/src/pages/Main/Main.tsx
Labels: FE, BE, 작업완료

#181 [feature/173] Client Header에서 장바구니 개수를 렌더링
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/IconContainerStyle.ts
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/ShoppigCartIcon/ShoppingCartIcon.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/recoil/cartState.ts
Labels: FE, 작업완료

#179 [feature/] 관리자 페이지 주문 조회 화면 개발 및 대시보드 속 실시간 주문 현황 컴포넌트 개발
  backend/src/repository/order.list.repository.ts
  frontend/admin/src/App.tsx
  frontend/admin/src/apis/orderAPI.ts
  frontend/admin/src/hooks/useInterval.ts
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
  frontend/admin/src/pages/Main/Main.tsx
  frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTable.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderRow.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableBody.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableHead.tsx
  frontend/admin/src/types/Goods.ts
  frontend/admin/src/types/Order.ts
  frontend/admin/src/utils/dateHelper.ts
  frontend/admin/webpack.common.js
  frontend/admin/webpack.dev.js
  frontend/client/src/components/SideBar/RecentGoodsView.tsx
  frontend/client/src/hooks/useRecentGoodsHistory.ts
  frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
  frontend/client/src/pages/MyPage/MyOrderListView/MyOrderListView.tsx
  frontend/client/src/pages/MyPage/MyProfileView/MyProfileView.tsx
  frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
  frontend/client/src/recoil/recentGoodsState.ts
  frontend/client/webpack.dev.js
Labels: FE, 작업완료

#184 [feature/169] 대시보드 - Bar chart, Top Selling Category (컴포넌트 API 개발) , 제품 조회수 Column 추가 및 적용
  backend/src/controller/category.controller.ts
  backend/src/database.ts
  backend/src/entity/Goods.ts
  backend/src/repository/category.repository.ts
  backend/src/repository/goods.repository.ts
  backend/src/router/category.router.ts
  backend/src/service/category.service.ts
  backend/src/service/goods.service.ts
  backend/src/types/response/category.response.ts
  frontend/admin/src/apis/categoryAPI.ts
  frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
  frontend/admin/src/pages/Main/Main.tsx
  frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategory/TopSellingCategory.tsx
  frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategoryList.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
  frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
  frontend/admin/src/theme/theme.ts
  frontend/admin/src/types/Category.ts
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
Labels: FE, BE, 작업완료

#172 [feuatre/154] 장바구니 관련 비즈니스 로직 완성
  backend/src/repository/goods.repository.ts
  backend/src/repository/order.list.repository.ts
  backend/src/service/cart.service.ts
  backend/src/service/order.service.ts
  backend/src/types/request/order.request.ts
  frontend/client/src/apis/orderAPI.ts
  frontend/client/src/hooks/usePushToOrderPage.ts
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/recoil/orderState.ts
Labels: FE, BE, 작업완료

#190 [feature/188] 리뷰 entity 추가
  backend/src/entity/Review.ts
  backend/src/entity/ReviewImg.ts
Labels: BE, 작업완료

#189 [feature/186] 최근 상품 조회하는 사이드바 UI 수정 및 각종 사소한 Client UI/UX 수정
  backend/src/database.ts
  backend/src/entity/DeliveryInfo.ts
  backend/src/entity/Order.ts
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTable.tsx
  frontend/admin/webpack.dev.js
  frontend/client/src/App.tsx
  frontend/client/src/components/Header/Header.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/IconContainerStyle.ts
  frontend/client/src/components/PromotionCarousel/PromotionCarousel.tsx
  frontend/client/src/components/SideBar/RecentGoodsView.tsx
  frontend/client/src/components/SideBar/SideBar.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/InfoContent/InfoContent.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
Labels: FE

#193 [feature/187] review 작성 Form (이미지 업로드, Contents, 별점) 컴포넌트
  frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
  frontend/client/src/components/ReviewForm/ReviewForm.tsx
  frontend/client/src/components/ReviewForm/ReviewFormContents/ReviewFormContents.tsx
  frontend/client/src/components/ReviewForm/ReviewFormFooter/ReviewFormFooter.tsx
  frontend/client/src/components/ReviewForm/ReviewFormHeader/ReviewFormHeader.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewFormImage.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageList/ReviewFormPreviewImage/ReviewFormPreviewImage.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageList/ReviewImageList.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageUploadButton/ReviewImageUploadButton.tsx
  frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewFormRate.tsx
  frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewRate/RateStar/RateStar.tsx
  frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewRate/ReviewRate.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/portal/ReviewFormModal/ReviewFormModal.tsx
Labels: FE, 작업완료

#201 [feature/195] 주문 상세 보기 모달 추가 및 여러 모달 BlurBackground 클릭시 닫히도록 수정
  frontend/admin/src/components/Header/DashboardIcon/DashboardIcon.tsx
  frontend/admin/src/components/Header/GoodsAdminIcon/GoodsAdminIcon.tsx
  frontend/admin/src/components/Header/LogoIcon/LogoIcon.tsx
  frontend/admin/src/components/Header/OrderAdminIcon/OrderAdminIcon.tsx
  frontend/admin/src/components/Header/PromotionAdminIcon/PromotionAdminIcon.tsx
  frontend/admin/src/hooks/useInterval.ts
  frontend/admin/src/pages/GoodsAdmin/GoodsAdmin.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
  frontend/admin/src/pages/OrderAdmin/OrderAdmin.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTable.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderRow.tsx
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderTableBody.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionAdmin.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionList.tsx
  frontend/admin/src/portal/ConfirmModal/ConfirmModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/OrderModal/OrderCard.tsx
  frontend/admin/src/portal/OrderModal/OrderGoods.tsx
  frontend/admin/src/portal/OrderModal/OrderModal.tsx
  frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
  frontend/admin/webpack.dev.js
Labels: FE, 작업완료

#202 [feature/199] 관리자 페이지 상품 정렬 기능 추가 및 대시보드, 프로모션 관리 UI 수정
  backend/src/controller/goods.controller.ts
  backend/src/controller/promotion.controller.ts
  backend/src/repository/promotion.repository.ts
  backend/src/router/promotion.router.ts
  backend/src/service/category.service.ts
  backend/src/service/goods.service.ts
  backend/src/service/promotion.service.ts
  backend/src/types/request/goods.request.ts
  backend/src/types/response/promotion.response.ts
  frontend/admin/src/apis/goodsAPI.ts
  frontend/admin/src/apis/promotionAPI.ts
  frontend/admin/src/pages/GoodsAdmin/GoodsAdmin.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTable.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableBody.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHeadData/GoodsTableHeadData.tsx
  frontend/admin/src/pages/Main/CategoryBarChart/CategoryBarChart.tsx
  frontend/admin/src/pages/Main/CategoryPieChart/CategoryPieChart.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
  frontend/admin/src/pages/Main/Main.tsx
  frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategory/TopSellingCategory.tsx
  frontend/admin/src/pages/Main/TopSellingCategoryList/TopSellingCategoryList.tsx
  frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoods/TopSellingGoods.tsx
  frontend/admin/src/pages/Main/TopSellingGoodsList/TopSellingGoodsList.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionAdmin.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionList.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionViewChart/PromotionViewChart.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/theme/theme.ts
  frontend/admin/src/types/Chart.ts
  frontend/admin/src/types/Goods.ts
  frontend/admin/src/types/Promotion.ts
  frontend/client/src/apis/goodsAPI.ts
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
Labels: FE, BE, 작업완료

#205 [feature/191] ReviewContainer 데이터 흐름 작성
  frontend/client/src/apis/reviewAPI.ts
  frontend/client/src/components/AwesomeButton/AwesomeButton.tsx
  frontend/client/src/components/Dim/Dim.tsx
  frontend/client/src/components/ReviewCard/ReviewCard.tsx
  frontend/client/src/components/ReviewContainer/ReviewContainer.tsx
  frontend/client/src/components/ReviewContainer/ReviewContainerHeader/ReviewContainerHeader.tsx
  frontend/client/src/components/ReviewContainer/ReviewEmpty/ReviewEmpty.tsx
  frontend/client/src/components/ReviewContainer/ReviewImageModal/ReviewImageModal.tsx
  frontend/client/src/components/ReviewContainer/ReviewList/ReviewList.tsx
  frontend/client/src/components/ReviewContainer/ReviewLoading/ReviewLoading.tsx
  frontend/client/src/components/ReviewList/ReviewList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/types/Review.ts
Labels: FE, 작업완료

#207 [feature/203] Lighthouse 의 성능 지표를 개선하기 위한 작업
  frontend/admin/package-lock.json
  frontend/admin/package.json
  frontend/admin/src/components/GoodsSearchInput/GoodsSearchInput.tsx
  frontend/admin/src/components/Header/DashboardIcon/DashboardIcon.tsx
  frontend/admin/src/components/Header/GoodsAdminIcon/GoodsAdminIcon.tsx
  frontend/admin/src/components/Header/OrderAdminIcon/OrderAdminIcon.tsx
  frontend/admin/src/components/Header/PromotionAdminIcon/PromotionAdminIcon.tsx
  frontend/admin/src/components/Paginator/Paginator.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHeadData/GoodsTableHeadData.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/ImageIconButton/ImageIconButton.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/PreviewImage/PreviewImage.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsImageUploader/PreviewOldImage/PreviewOldImage.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsPriceUploader/GoodsPriceUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsStockUploader/GoodsStockUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentLeft/GoodsTitleUploader/GoodsTitleUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsGreenUploader/GoodsGreenUploader.tsx
  frontend/admin/src/portal/OrderModal/OrderCard.tsx
  frontend/admin/src/portal/OrderModal/OrderModal.tsx
  frontend/admin/src/portal/PromotionUploadModal/PromotionImageUploader/PromotionImageButton/PromotionImageButton.tsx
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/src/components/AddressModals/ModalBar/ModalBar.tsx
  frontend/client/src/components/CheckButton/CheckButton.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/Header/HeaderBottom/CategoryToggle/CategoryToggle.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/MyPageIcon/MyPageIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/SearchIcon/SearchIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/HeaderIconContainer/ShoppigCartIcon/ShoppingCartIcon.tsx
  frontend/client/src/components/Header/HeaderBottom/SearchContainer/SearchContainer.tsx
  frontend/client/src/components/Paginator/Paginator.tsx
  frontend/client/src/components/ReviewContainer/ReviewContainerHeader/ReviewContainerHeader.tsx
  frontend/client/src/components/ReviewForm/ReviewFormHeader/ReviewFormHeader.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageList/ReviewFormPreviewImage/ReviewFormPreviewImage.tsx
  frontend/client/src/components/ReviewForm/ReviewFormImage/ReviewImageUploadButton/ReviewImageUploadButton.tsx
  frontend/client/src/components/ReviewForm/ReviewFormRate/ReviewRate/RateStar/RateStar.tsx
  frontend/client/src/components/SideBar/RecentGoodsView.tsx
  frontend/client/src/components/Star/Star.tsx
  frontend/client/src/components/Tag/index.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsAmountInput/CartGoodsAmountInput.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/NavItem.tsx
  frontend/client/src/portal/CartModal/CartModal.tsx
  frontend/client/src/portal/LoginModal/SigninForm/GithubSignin/GithubSignin.tsx
  frontend/client/src/portal/LoginModal/SigninForm/SampleSignin/SampleSignin.tsx
  frontend/client/webpack.dev.js
  frontend/client/webpack.prod.js
Labels: bug, FE, 작업완료, 문서

#210 [feature/209] Toast 기본 노출 시간 감소, 최대 노출 개수 로직 추가
  frontend/client/src/lib/ToastProvider/ToastProvider.tsx
Labels: FE, 작업완료

#215 [feature/214] 관리자페이지의 파이차트에서 정확한 상품 수를 출력하도록 수정했습니다.
  backend/src/controller/category.controller.ts
  backend/src/database.ts
  backend/src/entity/Category.ts
  backend/src/entity/Goods.ts
  backend/src/repository/category.repository.ts
  backend/src/router/category.router.ts
  backend/src/service/category.service.ts
  backend/src/types/response/category.response.ts
  frontend/admin/src/apis/categoryAPI.ts
  frontend/admin/src/pages/Main/CategoryPieChart/CategoryPieChart.tsx
Labels: FE, BE

#217 [feature/160] Admin으로 이동하는 Fab button, 숫자 애니메이션 롤링
  frontend/client/src/components/AdminFubButton/AdminFubButton.tsx
  frontend/client/src/components/RollingNumberMaker/RollingNumber/RollingNumber.tsx
  frontend/client/src/components/RollingNumberMaker/RollingNumberMaker.tsx
  frontend/client/src/constants/rollingNumber.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/Main/Main.tsx
Labels: FE, 작업완료

#218 [feature/213] 상품상세페이지 리뷰 컨테이너 마무리
  backend/src/controller/review.controller.ts
  backend/src/entity/Review.ts
  backend/src/repository/review.repository.ts
  backend/src/router/review.router.ts
  backend/src/service/review.service.ts
  backend/src/types/Review.ts
  frontend/client/src/apis/reviewAPI.ts
  frontend/client/src/components/ReviewContainer/ReviewContainer.tsx
  frontend/client/src/components/ReviewContainer/ReviewContainerHeader/ReviewContainerHeader.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
Labels: FE, BE, 작업완료

#221 [fix] review 레포지토리 오류
  backend/src/repository/review.repository.ts
Labels: bug, BE

#220 [feature/219] 관리자 페이지 상품 관리(삭제), 프로모션 UI 수정
  backend/src/repository/goods.repository.ts
  backend/src/repository/promotion.repository.ts
  backend/src/service/goods.service.ts
  backend/src/service/promotion.service.ts
  frontend/admin/src/components/GoodsSearchInput/GoodsSearchInput.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableBody/GoodsTableRow/GoodsTableRow.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/GoodsTableHead/GoodsTableHead.tsx
  frontend/admin/src/pages/GoodsAdmin/GoodsTable/Search/Search.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderCard/LiveOrderCard.tsx
  frontend/admin/src/pages/Main/LiveOrderList/LiveOrderList.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionAdmin.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionItem/PromotionItem.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionList/PromotionList.tsx
  frontend/admin/src/pages/PromotionAdmin/PromotionViewChart/PromotionViewChart.tsx
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsStateUploader/GoodsStateUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/UploadContentRight.tsx
  frontend/admin/src/portal/OrderModal/OrderCard.tsx
  frontend/admin/src/portal/PromotionUploadModal/PromotionImageUploader/PromotionImageButton/PromotionImageButton.tsx
  frontend/admin/src/portal/PromotionUploadModal/PromotionUploadModal.tsx
Labels: FE, BE

#264 [feature/250] 이슈에서 제보된 상품관련 버그 수정 (내용 참고!)
  backend/src/config/index.ts
  backend/src/constants/index.ts
  backend/src/controller/category.controller.ts
  backend/src/controller/goods.controller.ts
  backend/src/database.ts
  backend/src/repository/category.repository.ts
  backend/src/repository/goods.img.repository.ts
  backend/src/repository/goods.repository.ts
  backend/src/repository/user.repository.ts
  backend/src/repository/wish.repository.ts
  backend/src/router/category.router.ts
  backend/src/service/auth.service.ts
  backend/src/service/cart.service.ts
  backend/src/service/category.service.ts
  backend/src/service/goods.service.ts
  backend/src/service/order.service.ts
  backend/src/service/promotion.service.ts
  backend/src/service/review.service.ts
  backend/src/service/wish.service.ts
  frontend/admin/src/apis/categoryAPI.ts
  frontend/admin/src/portal/GoodsUploadModal/GoodsUploadModal.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsCategoryUploader/GoodsCategoryUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/GoodsStateUploader/GoodsStateUploader.tsx
  frontend/admin/src/portal/GoodsUploadModal/UploadContentRight/UploadContentRight.tsx
  frontend/admin/src/types/Category.ts
  frontend/admin/src/types/Goods.ts
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
  frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
Labels: FE, BE, 작업완료

#265 [feature/250] 주문 완료 후 cart 상태 최신화
  frontend/client/src/pages/Order/OrderPage.tsx
Labels: FE, 작업완료

#267 [feature/260] admin-order 유저 프로필 align 정렬 수정 및 react-helmet 적용
  frontend/admin/src/pages/OrderAdmin/OrderTable/OrderTableBody/OrderRow.tsx
  frontend/client/package-lock.json
  frontend/client/package.json
  frontend/client/src/App.tsx
  frontend/client/src/GlobalStyles.ts
  frontend/client/src/components/AddressModals/AddressCreateModal/AddressCreateModal.tsx
  frontend/client/src/components/AddressModals/AddressManageModal/AddressManageModal.tsx
  frontend/client/src/components/GoodsItem/GoodsItem.tsx
  frontend/client/src/components/GoodsItemList/GoodsItemList.tsx
  frontend/client/src/components/GoodsSection/GoodsSection.tsx
  frontend/client/src/index.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListContainer.tsx
  frontend/client/src/pages/Cart/CartGoodsListContainer/CartGoodsListItem/CartGoodsListItem.tsx
  frontend/client/src/pages/Cart/CartOrder/CartOrder.tsx
  frontend/client/src/pages/Cart/CartPage.tsx
  frontend/client/src/pages/Cart/EmptyCart/EmptyCart.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryFlag.tsx
  frontend/client/src/pages/CategoryGoods/CategoryGoodsList/CategoryGoodsList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsDetailPage.tsx
  frontend/client/src/pages/GoodsDetail/GoodsImageSection/ImageList/ImageList.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInfo/GoodsInfo.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsAmount/GoodsAmount.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsButtons/GoodsButtons.tsx
  frontend/client/src/pages/GoodsDetail/GoodsInteractive/GoodsInteractive.tsx
  frontend/client/src/pages/GoodsDetail/RelationSection/RelationSection.tsx
  frontend/client/src/pages/KeywordGoods/KeywordGoods.tsx
  frontend/client/src/pages/Main/Main.tsx
  frontend/client/src/pages/MyPage/MyAddressView/MyAddressView.tsx
  frontend/client/src/pages/MyPage/MyOrderListView/MyOrderListView.tsx
  frontend/client/src/pages/MyPage/MyOrderListView/OrderCard.tsx
  frontend/client/src/pages/MyPage/MyPageNavBar/MyPageNavBar.tsx
  frontend/client/src/pages/MyPage/MyProfileView/MyProfileView.tsx
  frontend/client/src/pages/MyPage/MyWishListView/MyWishListView.tsx
  frontend/client/src/pages/Order/AddressSection/AddressSection.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsList.tsx
  frontend/client/src/pages/Order/OrderGoodsList/OrderGoodsListItem/OrderGoodsListItem.tsx
  frontend/client/src/pages/Order/OrderPage.tsx
  frontend/client/src/pages/Order/PaymentRadioSelector/PaymentRadioSelector.tsx
  frontend/client/src/portal/CartModal/CartForm/CartForm.tsx
  frontend/client/src/portal/LoginModal/LoginModal.tsx
  frontend/client/src/portal/LoginModal/SigninForm/SampleSignin/SampleSignin.tsx
  frontend/client/src/portal/LoginModal/SigninForm/SigninForm.tsx
  frontend/client/src/portal/ReviewFormModal/ReviewFormModal.tsx
Labels: bug, FE, 작업완료

#268 fix: 메인 상품 리스트 버그 수정
  backend/src/service/goods.service.ts
  frontend/client/src/pages/Main/Main.tsx
Labels: bug, FE, BE

#269 [feature/253] 우편번호 validation 추가
  backend/src/service/user.address.service.ts
  frontend/client/src/components/AddressModals/AddressFormCore/AddressFormCore.tsx
Labels: bug, FE, BE, 작업완료
